[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma migrate deploy && npx prisma db seed && npm start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
